version: '3'
services:
  mongo:
    image: mongo
    restart: always
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    restart: always
    volumes:
      - ./app/node_modules
      - ./src:/app/src
      - ./test:/app/test
